[package]
name = "teamy_studio_cursor_info"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
crossterm.workspace = true
eyre.workspace = true
image.workspace = true
ratatui.workspace = true
teamy_studio_spatial.workspace = true
teamy_studio_terminal_core.workspace = true
windows = { workspace = true, features = [
    "std",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
