[package]
name = "teamy_studio_spatial"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
eyre.workspace = true
sguaba.workspace = true
uom.workspace = true
windows = { workspace = true, features = [
    "std",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
] }
