[package]
name = "teamy_studio_windows_dialogs"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
eyre = "0.6.12"
teamy_studio_win32_support = { path = "../teamy_studio_win32_support" }

[dependencies.windows]
version = "0.62.2"
default-features = false
features = [
    "std",
    "Win32_Foundation",
    "Win32_UI_Controls",
    "Win32_UI_WindowsAndMessaging",
]
