[package]
name = "teamy_studio_windows_audio"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
eyre.workspace = true
teamy_studio_paths.workspace = true
teamy_studio_win32_support.workspace = true
windows = { workspace = true, features = [
    "std",
    "Win32_Media_Audio",
    "Win32_System_Diagnostics_Debug",
    "Win32_UI_WindowsAndMessaging",
] }
